name: Publish package to the Maven Central Repository and GitHub Packages
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  release:
    types: [created]
  workflow_dispatch:
    inputs: null
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Install GPG secret key
        if: ${{ env.GPG_SECRET_KEY != null }}
        run: |
          # Install GPG secret key
          cat <(echo -e "${{ secrets.OSSRH_GPG_SECRET_KEY }}") | gpg --batch --import
          # Verify GPG secret key
          gpg --list-secret-keys --keyid-format LONG
        env:
          GPG_SECRET_KEY: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
      - name: Set up Java for publishing to GitHub Packages
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'zulu'
      - name: Publish to GitHub Packages
        run: mvn -B -Pgithub,sign -Dgpg.passphrase=${{ secrets.OSSRH_GPG_SECRET_KEY_PASSPHRASE }} clean deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Java for publishing to Maven Central Repository
        if: ${{ env.MAVEN_USERNAME != null }}
        uses: actions/setup-java@v3
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        with:
          java-version: '8'
          distribution: 'zulu'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Publish to the Maven Central Repository
        if: ${{ env.MAVEN_USERNAME != null }}
        run: mvn -B -Pmaven-central,sign -Dgpg.passphrase=${{ secrets.OSSRH_GPG_SECRET_KEY_PASSPHRASE }} clean deploy
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
