on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'zulu'
          cache: maven
      - name: Build with Maven
        run: mvn -B package site --file pom.xml
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          name: Release v${{ github.ref_name }}
          artifacts: "target/spring-task-scope*.jar"
